set nocompatible
filetype off

"""""""""""
" Plugins "
"""""""""""
source ~/.vim/plugged/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'

Plug 'vim-airline/vim-airline' | Plug 'vim-airline/vim-airline-themes'
Plug 'edkolev/tmuxline.vim'
Plug 'mhartington/oceanic-next'
Plug 'ryanoasis/vim-devicons'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-rsi'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'Lokaltog/vim-easymotion'
Plug 'w0rp/ale'
Plug 'sbdchd/neoformat'
Plug 'ervandew/supertab'
Plug 'mileszs/ack.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'rking/ag.vim'
Plug 'wakatime/vim-wakatime'
Plug 'mattn/gist-vim' | Plug 'mattn/webapi-vim'
" Specific file types
Plug 'tpope/vim-haml'
Plug 'groenewege/vim-less'
Plug 'ap/vim-css-color'
Plug 'pangloss/vim-javascript'
Plug 'ElmCast/elm-vim', { 'for': 'elm' }
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mxw/vim-jsx'
Plug 'plasticboy/vim-markdown'
Plug 'kchmck/vim-coffee-script'

call plug#end()
filetype plugin indent on

"""""""""""
" General "
"""""""""""
set encoding=utf8       " force utf8 encoding
set t_Co=256            " enable 256 colors
set visualbell          " use visual bell
set mouse=a             " enables mouse handling
set backspace=2         " allow backspacing over indent, eol, and start
set pastetoggle=<F2>    " map key for toggling pastemode
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set foldmethod=syntax
set foldlevelstart=20

nnoremap ; :
nmap , \
map <Leader>ve :tabedit ~/.vimrc<CR>
map <Leader>vs :source ~/.vimrc<CR>
map f <Leader><Leader>f
map F <Leader><Leader>F
map <Leader>ws :w !sudo tee %<CR>
" clears search highlighting
noremap <CR> :noh<CR><CR>
" removes trailing spaces with F5
noremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>
map gr :tabprev<CR>
map <S-k> r<CR>k$

map <C-k> :bn<CR>
map <C-j> :bp<CR>
map <C-h> :bd<CR>

imap jj <Esc>
imap kk <Esc>
imap jk <Esc>
" disable arrowkeys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

"""""""""""""""""
" Style Options "
"""""""""""""""""
syntax on               " enable syntax highlighting
set nospell             " disable spell checking by default
set number              " line numbers
set cursorline          " current line indicator
set scrolloff=14        " adds padding to the current line
set showmatch           " highlights matching bracket
set splitright          " sp opens new file in right pane
set splitbelow          " vsp opens new file in bottom pane

set background=dark
let g:solarized_termcolors=16
colorscheme solarized
let g:colors_name='solarized'
set laststatus=2
set noshowmode          " hide the current mode
set ttimeoutlen=100

" Whitespace
set listchars=tab:→\ ,nbsp:·,trail:$
set list
let &colorcolumn=join(range(81,300),",")
highlight ColorColumn ctermbg=0 guibg=#808080
highlight SignColumn ctermbg=232 guibg=#000000

" Airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#hunks#enabled = 1
let g:airline#extensions#whitespace#enabled = 1

" Gitgutter
let g:gitgutter_sign_added = '|'
let g:gitgutter_sign_modified = '|'
let g:gitgutter_sign_removed = '|'
let g:gitgutter_sign_removed_first_line = '|'
let g:gitgutter_sign_modified_removed = '|'

" Nerdtree
map <Leader>n :NERDTreeToggle<CR>
map <C-n>  :NERDTreeToggle<CR>

" Ctrl P
map <C-l> :CtrlPBuffer<CR>

" Markdown
let g:vim_markdown_folding_disabled=1

"""""""""""""""""""""""""""
" Indentation and spacing "
"""""""""""""""""""""""""""
set autoindent          " auto indenting
set expandtab           " spaces instead of tabs
set smarttab            " interprets consecutive spaces as tabs
set shiftwidth=4        " tab = 4 spaces
set softtabstop=4

"""""""""""""
" Searching "
"""""""""""""
set incsearch           " incremental searching
set hlsearch            " highlight matching results
set ignorecase          " ignore case in search
set smartcase           " override ignorecase if capital letter is used

"""""""""""""""""""
" Command options "
"""""""""""""""""""
set showcmd             " shows command information at bottom
set wildmenu            " autocomplete commands

" Load local config
if filereadable(glob("$HOME/.vimrc.local"))
    source $HOME/.vimrc.local
endif
