set nocompatible
filetype off

"""""""""""
" Plugins "
"""""""""""
set rtp+=~/.vim/bundle/vundle
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'bling/vim-airline'
Bundle 'flazz/vim-colorschemes'
Bundle 'scrooloose/nerdtree'
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-fugitive'
Bundle 'kien/ctrlp.vim'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'scrooloose/syntastic'
Bundle 'ervandew/supertab'
Bundle 'mileszs/ack.vim'
Bundle 'rking/ag.vim'
Bundle 'groenewege/vim-less'
Bundle 'skammer/vim-css-color'

filetype plugin indent on

"""""""""""
" General "
"""""""""""
set encoding=utf8       " force utf8 encoding
set visualbell          " use visual bell
set mouse=a             " enables mouse handling
set backspace=2         " allow backspacing over indent, eol, and start
set pastetoggle=<F2>    " map key for toggling pastemode
nnoremap ; :
imap jj <Esc>
imap kk <Esc>
imap jk <Esc>
" disable arrowkeys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

"""""""""""""""""
" Style Options "
"""""""""""""""""
syntax on               " enable syntax highlighting
set nospell             " disable spell checking by default
set number              " line numbers
set cursorline          " current line indicator
set scrolloff=14        " adds padding to the current line
set showmatch           " highlights matching bracket

colorscheme mustang
let g:colors_name='mustang'
set laststatus=2
set noshowmode          " hide the current mode
set ttimeoutlen=100

" Whitespace
set listchars=tab:→\ ,nbsp:·,trail:$
set list

" Airline
set t_Co=256
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#hunks#enabled = 1
let g:airline#extensions#whitespace#enabled = 1

" Nerdtree
autocmd vimenter * if !argc() | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

"""""""""""""""""""""""""""
" Indentation and spacing "
"""""""""""""""""""""""""""
set autoindent          " auto indenting
set expandtab           " spaces instead of tabs
set smarttab            " interprets consecutive spaces as tabs
set shiftwidth=4        " tab = 4 spaces
set softtabstop=4
set nowrap              " disables line wrapping

"""""""""""""
" Searching "
"""""""""""""
set incsearch           " incremental searching
set hlsearch            " highlight matching results
set ignorecase          " ignore case in search
set smartcase           " override ignorecase if capital letter is used

"""""""""""""""""""
" Command options "
"""""""""""""""""""
set showcmd             " shows command information at bottom
set wildmenu            " autocomplete commands
set autochdir           " automatically change directories to current file
