set nocompatible
filetype off

"""""""""""
" Plugins "
"""""""""""
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

Plugin 'bling/vim-airline'
Plugin 'flazz/vim-colorschemes'
Plugin 'scrooloose/nerdtree'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'
Plugin 'kien/ctrlp.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/syntastic'
Plugin 'Valloric/YouCompleteMe'
Plugin 'mileszs/ack.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'rking/ag.vim'
" Specific file types
Plugin 'tpope/vim-haml'
Plugin 'groenewege/vim-less'
Plugin 'ap/vim-css-color'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'plasticboy/vim-markdown'
Plugin 'kchmck/vim-coffee-script'

call vundle#end()
filetype plugin indent on

"""""""""""
" General "
"""""""""""
set encoding=utf8       " force utf8 encoding
set t_Co=256            " enable 256 colors
set visualbell          " use visual bell
set mouse=a             " enables mouse handling
set backspace=2         " allow backspacing over indent, eol, and start
set pastetoggle=<F2>    " map key for toggling pastemode
set wildignore+=*/tmp/*,*.so,*.swp,*.zip     " MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe  " Windows
set foldmethod=syntax
set foldlevelstart=20


nnoremap ; :
nmap , \
map <Leader>ve :tabedit ~/.vimrc<CR>
map <Leader>vs :source ~/.vimrc<CR>
map f <Leader><Leader>f
map F <Leader><Leader>F
map <Leader>ws :w !sudo tee %<CR>
" clears search highlighting
noremap <CR> :noh<CR><CR>
" removes trailing spaces with F5
noremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>
map gr :tabprev<CR>
map <S-k> r<CR>k$

map <C-k> :bn<CR>
map <C-j> :bp<CR>
map <C-i> :bd<CR>

imap jj <Esc>
imap kk <Esc>
imap jk <Esc>
" disable arrowkeys
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

"""""""""""""""""
" Style Options "
"""""""""""""""""
syntax on               " enable syntax highlighting
set nospell             " disable spell checking by default
set number              " line numbers
set cursorline          " current line indicator
set scrolloff=14        " adds padding to the current line
set showmatch           " highlights matching bracket

colorscheme mustang
let g:colors_name='mustang'
set laststatus=2
set noshowmode          " hide the current mode
set ttimeoutlen=100

" Whitespace
set listchars=tab:→\ ,nbsp:·,trail:$
set list
let &colorcolumn=join(range(81,300),",")
highlight ColorColumn ctermbg=235 guibg=#262626
highlight SignColumn ctermbg=232 guibg=#000000

" Airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#hunks#enabled = 1
let g:airline#extensions#whitespace#enabled = 1

" Gitgutter
let g:gitgutter_sign_added = '|'
let g:gitgutter_sign_modified = '|'
let g:gitgutter_sign_removed = '|'
let g:gitgutter_sign_removed_first_line = '|'
let g:gitgutter_sign_modified_removed = '|'

" Nerdtree
map <Leader>n :NERDTreeToggle<CR>
map <C-n>  :NERDTreeToggle<CR>

" Ctrl P
map <C-l> :CtrlPBuffer<CR>

" Markdown
let g:vim_markdown_folding_disabled=1

"""""""""""""""""""""""""""
" Indentation and spacing "
"""""""""""""""""""""""""""
set autoindent          " auto indenting
set expandtab           " spaces instead of tabs
set smarttab            " interprets consecutive spaces as tabs
set shiftwidth=4        " tab = 4 spaces
set softtabstop=4

"""""""""""""
" Searching "
"""""""""""""
set incsearch           " incremental searching
set hlsearch            " highlight matching results
set ignorecase          " ignore case in search
set smartcase           " override ignorecase if capital letter is used

"""""""""""""""""""
" Command options "
"""""""""""""""""""
set showcmd             " shows command information at bottom
set wildmenu            " autocomplete commands

" Load local config
if filereadable(glob("$HOME/.vimrc.local"))
    source $HOME/.vimrc.local
endif
