#!/bin/bash
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[[ -f ~/.wallpaper ]] && xloadimage -onroot -fullscreen ~/.wallpaper
xsetroot -cursor_name left_ptr
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 3 --transparent true --alpha 0 --tint 0x000000 --height 17 --margin 2 &
xscreensaver -no-splash &
syndaemon -i .5 -K -t -R -d
nm-applet &
dropboxd &
xflux -z 01904 --nofork
exec xmonad
