# Path to your oh-my-zsh configuration.
ZSH=$HOME/.zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(bower django gem git gitignore git-extras github npm pip python rails rsync ruby sublime svn wakeonlan zsh_reload)

# Linux
if [ "$(uname)" = "Linux" ]; then
    plugins+=(archlinux command-not-found sudo systemd)
# Windows
elif [ "$(uname)" = "CYGWIN*" ]; then
    plugins+=()
# Mac
elif [ "$(uname)" = "Darwin" ]; then
    plugins+=(brew osx textmate sudo)
fi

# Custom bin files
if [[ -d $HOME/.bin ]] then
    export PATH=$PATH:$HOME/.bin
fi
if [[ -d $HOME/.binprivate ]] then
    export PATH=$PATH:$HOME/.binprivate
fi

# virtualenv
if [[ -d $HOME/.virtualenvs ]] then
    plugins+=(virtualenv virtualenvwrapper)
fi
# gems
if [[ -d $HOME/.gem/ruby ]] then
    for rbbin in `find $HOME/.gem/ruby -mindepth 1 -maxdepth 1 -type d`
    do
        export PATH=$PATH:$rbbin/bin
    done
fi
# rbenv
if [[ -d $HOME/.rbenv ]] then
    plugins+=(rbenv)
    export PATH=$PATH:$HOME/.rbenv/bin/
    eval "$(rbenv init -)"
fi

# Include any local changes
if [[ -a $HOME/.zshrc.local ]] then
    source $HOME/.zshrc.local
fi

source $ZSH/oh-my-zsh.sh
